# Generated by Django 4.2 on 2023-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_s',
            name='Contact_details',
            field=models.CharField(choices=[('Number', ''), ('Email', '')], max_length=120),
        ),
    ]
