# Generated by Django 4.2 on 2023-05-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0003_api_s_email_api_s_location_api_s_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_s',
            old_name='Location',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='api_s',
            name='Contact_details',
        ),
    ]
